services:
  canventory:
    container_name: "canventory"
    restart: "unless-stopped"

    build:
      context: "."
      dockerfile: "Dockerfile"

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"
    volumes:
      - "./uploads:/app/uploads"
    env_file:
      - ".env"

  postgres:
    container_name: "canventory-postgres"
    image: "postgres:16-alpine"
    restart: "unless-stopped"
    env_file:
      - ".env"
    volumes:
      - "./data:/var/lib/postgresql/data"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-canventory} -d ${POSTGRES_DB:-canventory}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
